### ISSUE TITLE
Unable to Load VIC::PIC::P16F690

### ISSUE THREAD

**Issue by mnjrupp** [selectiveintellect/vic#3]
Running on Windows 7 with Strawberry Perl. I did have to "cpan force install"  because the multidimensional and bareword:: would not install using cpan. Here is the actual error when trying to compile the helloworld.vic example.

Unable to load VIC::PIC::P16F690: Only one role supported at a time by with at C
:/Dwimperl/perl/site/lib/Moo.pm line 24, <> line 1.
Compilation failed in require at (eval 98) line 1, <> line 1.
 at C:/Dwimperl/perl/site/lib/VIC/Receiver.pm line 60

**Comment by vikasnkumar** [comment]
Hello. Please provide your Strawberry Perl version. I will test and fix this issue. 

Thanks.

**Comment by vikasnkumar** [comment]
Please install using `App::cpanminus`. The command is `cpanm VIC`. That should work. However, if there is still a problem let me know. I will test with the latest Strawberry Perl and verify.

**Comment by vikasnkumar** [comment]
Hello @mnjrupp, 
I just tested with the latest Strawberry Perl 5.22 64-bit on Windows 7 64-bit and had no issues with installation using `App::cpanminus`. I recommend using that to install.

**Comment by mnjrupp** [comment]
Thanks @vikasnkumar . I will try it out and let you know.

**Comment by vikasnkumar** [comment]
Thank you. I would really appreciate your feedback, if any.

**Comment by mnjrupp** [comment]
@vikasnkumar  Here is the build log when using the cpanm VIC command:

cpanm (App::cpanminus) 1.7040 on perl 5.022001 built for MSWin32-x64-multi-thread
Work directory is C:\Users\Michael/.cpanm/work/1458618710.9548
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.15
Falling back to Archive::Tar 2.04
Searching VIC () on cpanmetadb ...
--> Working on VIC
Fetching http://www.cpan.org/authors/id/V/VI/VIKAS/VIC-0.28.tar.gz
-> OK
Unpacking VIC-0.28.tar.gz
Entering VIC-0.28
Checking configure dependencies from META.json
Checking if you have Module::Build 0.4005 ... Yes (0.4216)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.04)
Configuring VIC-0.28
Running Build.PL
-> N/A
-> FAIL Configure failed for VIC-0.28. See C:\Users\Michael.cpanm\work\1458618710.9548\build.log for details.

**Comment by vikasnkumar** [comment]
On 03/21/2016 11:56 PM, mnjrupp wrote:

> See C:\Users\Michael.cpanm\work\1458618710.9548\build.log for details.
> Can you provide the contents of the above file instead ?

Thanks.

**Comment by mnjrupp** [comment]
@vikasnkumar I pasted the contents from the file. I thought it was rather useless myself :-)

I had previously tried to install using cpan before opening this ticket and it was very verbose in it's output, as you can imagine. What is the purpose of using cpanm over cpan? I'm curious. Would you rather have the error log of cpan?

**Comment by vikasnkumar** [comment]
@mnjrupp,

`cpanm` is the better way to install perl packages nowadays. It handles
dependencies much better.

In any case, I tried the following from the Perl commandline shell
provided by Strawberry Perl.

```
    cpan -i VIC
```

and it worked.

Try the VIC version 0.29, and let me know what the verbose log using
`cpan` is.

Do you have some dependencies not installing correctly ? Such as Pegex
or similar ?

Thanks

**Comment by mnjrupp** [comment]
First off. Why did it try and install version .28 instead of .29?
Also there were two modules under cpan that did not install properly. I'm not at my machine now (at work) but it had to do with the bareword::filehandles and multidimensional. I'm not at my PC since I'm at work but I can re-run cpan and paste the output.

**Comment by vikasnkumar** [comment]
Well, I don't know about why it tried 0.28. Maybe the cpan was using an
older index. Plus i made a new release last night to improve builds. So
far CPANTesters has not sent me any errors.

I got rid of the bareword-filehandles and multidimensional. I don't use
them anymore. So you should have no issues now.

You may want to use `cpanm` instead of `cpan` still. It works better.

Let me know whenever you get a chance, no hurry.

**Comment by mnjrupp** [comment]
Ok, I will try that tonight. FYI. at work we use "ActivePerl" which has the prebuilt modules. I was able to install VIC without any issues. But at home I rather use Strawberry so I was hoping to resolve this. I really like what you have done with programming PICs using perl.

**Comment by mnjrupp** [comment]
Yes! I was not able to install using cpanm (There might be an issue with my version, I didn't try to update) but I was able to install using cpan. It installed the dependencies like XXX with no errors and passed the tests. Thanks for your help on this.
Another question. Do you have any future plans to add the PIC16F877(a) to the list of supported PICs?

**Comment by vikasnkumar** [comment]
There are literally 100s of PICs and that's why the task is so hard for
one person to do it in free time. Plus I do not have a PIC16F877 on me
at the moment to test in real-time.

However, unless you need a special feature like SPI/I2C/UART, it should
be easy to add and test by reading the datasheet and creating a class
for it.

**Comment by mnjrupp** [comment]
Thanks, can you use gpsim to simulate the PIC16F877 for testing or are you referring to hardware?

**Comment by vikasnkumar** [comment]
On 03/23/2016 01:56 PM, mnjrupp wrote:

> Thanks, can you use gpsim to simulate the PIC16F877 for testing or are
> you referring to hardware?

Yes I would use gpsim to simulate. But I also like to manually verify
with hardware, that's why the task is so cumbersome. The P16F690 I have
verified in both gpsim and hardware. The rest only in gpsim since I
didn't get time to verify in hardware.

But yea, for immediate use I can do the gpsim only verification.

Give me a week or two to figure out time to add the chip.

--Vikas

**Comment by mnjrupp** [comment]
@vikasnkumar  you don't have to be in a hurry. I can use gpsim to simulate outside of VIC until available. Thanks for your help on this. I'm currently going through a PIC tutorial that uses the 16F877.

**Comment by vikasnkumar** [comment]
Oh ok.

You should be able to switch to 16F690 then. Most or all the tutorials
on the web do nothing complex, and should work with PIC16F690. In fact I
have plenty of examples in VIC that you can view on the Github repo.
Ideally they should have gotten installed but seems like they haven't
which I will fix soon.

P16F877 is outdated and not sold by Microchip anymore. they recommend
P16F887.

I look forward to bug reports, if any.

**Comment by mnjrupp** [comment]
http://ww1.microchip.com/downloads/en/DeviceDoc/41291D.pdf

Page 273, differences between the F877 and F887.

Would adding the F887 be more advantageous? It seems the newest PIC16 you offer is the F690.
